steps:
  # Install dependencies
 - name: python
   entrypoint: 'bash'
   args: ['-c','pip3 install -r requirements.txt']
 # Docker Build
 - name: 'gcr.io/cloud-builders/docker'
   args: ['build', '-t','us-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY_REPO}/cbpoc2:${SHORT_SHA}', '.']
  # Docker push to Google Artifact Registry
 - name: 'gcr.io/cloud-builders/docker'
   args: ['push',  'us-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY_REPO}/cbpoc2:${SHORT_SHA}']
  # Deploy to Cloud Run
 - name: google/cloud-sdk
   args: ['gcloud', 'run', 'deploy', 'cbpoc2', '--image=us-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY_REPO}/cbpoc2:${SHORT_SHA}','--region', 'us-central1', '--platform', 'managed', '--allow-unauthenticated']
options:
  logging: CLOUD_LOGGING_ONLY
